// AUTO-GENERATED by scripts/build-content.mjs — do not edit manually

export type OgEntry = {
  weekTitle: string;
  sermonSeries: string;
  dayTitle: string;
  reference: string;
  accent: string;
  dayNum: number;
  publishDate: string | null;
};

export const ogData: Record<string, OgEntry> = {
  "the-risk-of-success/1": {
    "weekTitle": "The Risk of Success",
    "sermonSeries": "Trust & Obey",
    "dayTitle": "The Weight Is the Assignment",
    "reference": "Joshua 1:2 ESV",
    "accent": "#937B5A",
    "dayNum": 1,
    "publishDate": "2026-04-20"
  },
  "the-risk-of-success/2": {
    "weekTitle": "The Risk of Success",
    "sermonSeries": "Trust & Obey",
    "dayTitle": "Grace Before the Command",
    "reference": "Joshua 1:5 ESV",
    "accent": "#937B5A",
    "dayNum": 2,
    "publishDate": "2026-04-21"
  },
  "the-risk-of-success/3": {
    "weekTitle": "The Risk of Success",
    "sermonSeries": "Trust & Obey",
    "dayTitle": "No Detours",
    "reference": "Joshua 1:7 ESV",
    "accent": "#937B5A",
    "dayNum": 3,
    "publishDate": "2026-04-22"
  },
  "the-risk-of-success/4": {
    "weekTitle": "The Risk of Success",
    "sermonSeries": "Trust & Obey",
    "dayTitle": "Go Back",
    "reference": "Joshua 8:1 ESV",
    "accent": "#937B5A",
    "dayNum": 4,
    "publishDate": "2026-04-23"
  },
  "the-risk-of-success/5": {
    "weekTitle": "The Risk of Success",
    "sermonSeries": "Trust & Obey",
    "dayTitle": "The Ground Beneath",
    "reference": "Joshua 1:9 ESV",
    "accent": "#937B5A",
    "dayNum": 5,
    "publishDate": "2026-04-24"
  },
  "surrender-the-moment/1": {
    "weekTitle": "Surrender The Moment",
    "sermonSeries": "Trust & Obey",
    "dayTitle": "Already Given",
    "reference": "Joshua 1:3 ESV",
    "accent": "#937B5A",
    "dayNum": 1,
    "publishDate": "2026-04-13"
  },
  "surrender-the-moment/2": {
    "weekTitle": "Surrender The Moment",
    "sermonSeries": "Trust & Obey",
    "dayTitle": "The Danger of Settling",
    "reference": "Joshua 1:4 ESV",
    "accent": "#937B5A",
    "dayNum": 2,
    "publishDate": "2026-04-14"
  },
  "surrender-the-moment/3": {
    "weekTitle": "Surrender The Moment",
    "sermonSeries": "Trust & Obey",
    "dayTitle": "The Cost of the Next Step",
    "reference": "Joshua 1:7 ESV",
    "accent": "#937B5A",
    "dayNum": 3,
    "publishDate": "2026-04-15"
  },
  "surrender-the-moment/4": {
    "weekTitle": "Surrender The Moment",
    "sermonSeries": "Trust & Obey",
    "dayTitle": "Conquering Power",
    "reference": "Joshua 1:5 ESV",
    "accent": "#937B5A",
    "dayNum": 4,
    "publishDate": "2026-04-16"
  },
  "surrender-the-moment/5": {
    "weekTitle": "Surrender The Moment",
    "sermonSeries": "Trust & Obey",
    "dayTitle": "Constant Presence",
    "reference": "Psalm 119:89-90 CSB",
    "accent": "#937B5A",
    "dayNum": 5,
    "publishDate": "2026-04-17"
  },
  "lost-sheep/1": {
    "weekTitle": "Lost Sheep",
    "sermonSeries": "Lost Sheep",
    "dayTitle": "The Shepherd Is Counting",
    "reference": "Luke 15:4 ESV",
    "accent": "#4F00EE",
    "dayNum": 1,
    "publishDate": "2026-04-06"
  },
  "lost-sheep/2": {
    "weekTitle": "Lost Sheep",
    "sermonSeries": "Lost Sheep",
    "dayTitle": "Lost and Don't Know It",
    "reference": "Isaiah 53:6 ESV",
    "accent": "#4F00EE",
    "dayNum": 2,
    "publishDate": "2026-04-07"
  },
  "lost-sheep/3": {
    "weekTitle": "Lost Sheep",
    "sermonSeries": "Lost Sheep",
    "dayTitle": "Defenseless",
    "reference": "Matthew 9:36 ESV",
    "accent": "#4F00EE",
    "dayNum": 3,
    "publishDate": "2026-04-08"
  },
  "lost-sheep/4": {
    "weekTitle": "Lost Sheep",
    "sermonSeries": "Lost Sheep",
    "dayTitle": "Carried Home",
    "reference": "Luke 15:5 ESV",
    "accent": "#4F00EE",
    "dayNum": 4,
    "publishDate": "2026-04-09"
  },
  "lost-sheep/5": {
    "weekTitle": "Lost Sheep",
    "sermonSeries": "Lost Sheep",
    "dayTitle": "Who for the Joy",
    "reference": "Hebrews 12:2 ESV",
    "accent": "#4F00EE",
    "dayNum": 5,
    "publishDate": "2026-04-10"
  },
  "until/1": {
    "weekTitle": "UNTIL",
    "sermonSeries": "Leaving the 99",
    "dayTitle": "Until",
    "reference": "Luke 15:4 ESV",
    "accent": "#2D4A3E",
    "dayNum": 1,
    "publishDate": "2026-03-30"
  },
  "until/2": {
    "weekTitle": "UNTIL",
    "sermonSeries": "Leaving the 99",
    "dayTitle": "The Arrival",
    "reference": "Luke 19:28–35 ESV",
    "accent": "#2D4A3E",
    "dayNum": 2,
    "publishDate": "2026-03-31"
  },
  "until/3": {
    "weekTitle": "UNTIL",
    "sermonSeries": "Leaving the 99",
    "dayTitle": "The Applause",
    "reference": "Luke 19:36–40 ESV",
    "accent": "#2D4A3E",
    "dayNum": 3,
    "publishDate": "2026-04-01"
  },
  "until/4": {
    "weekTitle": "UNTIL",
    "sermonSeries": "Leaving the 99",
    "dayTitle": "The Anguish",
    "reference": "Luke 19:41–44 ESV",
    "accent": "#2D4A3E",
    "dayNum": 4,
    "publishDate": "2026-04-02"
  },
  "until/5": {
    "weekTitle": "UNTIL",
    "sermonSeries": "Leaving the 99",
    "dayTitle": "The Search Continues",
    "reference": "Romans 10:9 ESV",
    "accent": "#2D4A3E",
    "dayNum": 5,
    "publishDate": "2026-04-03"
  },
  "finding-the-joy/1": {
    "weekTitle": "Finding the Joy That Finds the One",
    "sermonSeries": "Leaving the 99",
    "dayTitle": "The Destination Is Joy",
    "reference": "Luke 15:7 ESV",
    "accent": "#2D4A3E",
    "dayNum": 1,
    "publishDate": "2026-03-23"
  },
  "finding-the-joy/2": {
    "weekTitle": "Finding the Joy That Finds the One",
    "sermonSeries": "Leaving the 99",
    "dayTitle": "What Makes Heaven Shout",
    "reference": "Zephaniah 3:17 ESV",
    "accent": "#2D4A3E",
    "dayNum": 2,
    "publishDate": "2026-03-24"
  },
  "finding-the-joy/3": {
    "weekTitle": "Finding the Joy That Finds the One",
    "sermonSeries": "Leaving the 99",
    "dayTitle": "The Joy That Endured the Cross",
    "reference": "Hebrews 12:2 ESV",
    "accent": "#2D4A3E",
    "dayNum": 3,
    "publishDate": "2026-03-25"
  },
  "finding-the-joy/4": {
    "weekTitle": "Finding the Joy That Finds the One",
    "sermonSeries": "Leaving the 99",
    "dayTitle": "The Comfort of the 99",
    "reference": "Luke 15:1-2 ESV",
    "accent": "#2D4A3E",
    "dayNum": 4,
    "publishDate": "2026-03-26"
  },
  "finding-the-joy/5": {
    "weekTitle": "Finding the Joy That Finds the One",
    "sermonSeries": "Leaving the 99",
    "dayTitle": "Looking for the One Looking for You",
    "reference": "Ezekiel 34:4 ESV",
    "accent": "#2D4A3E",
    "dayNum": 5,
    "publishDate": "2026-03-27"
  },
  "transmute/1": {
    "weekTitle": "Transmute",
    "sermonSeries": "Leaving the 99",
    "dayTitle": "The Day of Accounting",
    "reference": "2 Corinthians 5:10 ESV",
    "accent": "#2D4A3E",
    "dayNum": 1,
    "publishDate": "2026-03-16"
  },
  "transmute/2": {
    "weekTitle": "Transmute",
    "sermonSeries": "Leaving the 99",
    "dayTitle": "What the Replay Reveals",
    "reference": "Hebrews 4:13 ESV",
    "accent": "#2D4A3E",
    "dayNum": 2,
    "publishDate": "2026-03-17"
  },
  "transmute/3": {
    "weekTitle": "Transmute",
    "sermonSeries": "Leaving the 99",
    "dayTitle": "The Shrewdest Investment",
    "reference": "Luke 16:8–9 ESV",
    "accent": "#2D4A3E",
    "dayNum": 3,
    "publishDate": "2026-03-18"
  },
  "transmute/4": {
    "weekTitle": "Transmute",
    "sermonSeries": "Leaving the 99",
    "dayTitle": "Small Stuff and True Riches",
    "reference": "Luke 16:10–11 ESV",
    "accent": "#2D4A3E",
    "dayNum": 4,
    "publishDate": "2026-03-19"
  },
  "transmute/5": {
    "weekTitle": "Transmute",
    "sermonSeries": "Leaving the 99",
    "dayTitle": "Build Your Welcome Committee",
    "reference": "Luke 16:9 ESV",
    "accent": "#2D4A3E",
    "dayNum": 5,
    "publishDate": "2026-03-20"
  },
  "loving-the-lost/1": {
    "weekTitle": "Loving the Lost",
    "sermonSeries": "Multiply",
    "dayTitle": "Loving the Lost",
    "reference": "Luke 19:10 CSB",
    "accent": "#C8A96E",
    "dayNum": 1,
    "publishDate": "2026-03-02"
  },
  "loving-the-lost/2": {
    "weekTitle": "Loving the Lost",
    "sermonSeries": "Multiply",
    "dayTitle": "Loving the Lost",
    "reference": "Romans 3:23 CSB",
    "accent": "#C8A96E",
    "dayNum": 2,
    "publishDate": "2026-03-03"
  },
  "loving-the-lost/3": {
    "weekTitle": "Loving the Lost",
    "sermonSeries": "Multiply",
    "dayTitle": "Loving the Lost",
    "reference": "ESV",
    "accent": "#C8A96E",
    "dayNum": 3,
    "publishDate": "2026-03-04"
  },
  "loving-the-lost/4": {
    "weekTitle": "Loving the Lost",
    "sermonSeries": "Multiply",
    "dayTitle": "Loving the Lost",
    "reference": "Luke 10:33-34 CSB",
    "accent": "#C8A96E",
    "dayNum": 4,
    "publishDate": "2026-03-05"
  },
  "loving-the-lost/5": {
    "weekTitle": "Loving the Lost",
    "sermonSeries": "Multiply",
    "dayTitle": "Loving the Lost",
    "reference": "Titus 3:4-5 CSB",
    "accent": "#C8A96E",
    "dayNum": 5,
    "publishDate": "2026-03-06"
  },
  "do-you-love-me/1": {
    "weekTitle": "Do You Love Me",
    "sermonSeries": "Multiply",
    "dayTitle": "Do You Love Me",
    "reference": "Luke 5:1-11 ESV",
    "accent": "#C8A96E",
    "dayNum": 1,
    "publishDate": "2026-02-23"
  },
  "do-you-love-me/2": {
    "weekTitle": "Do You Love Me",
    "sermonSeries": "Multiply",
    "dayTitle": "Do You Love Me",
    "reference": "John 21:1-3 ESV",
    "accent": "#C8A96E",
    "dayNum": 2,
    "publishDate": "2026-02-24"
  },
  "do-you-love-me/3": {
    "weekTitle": "Do You Love Me",
    "sermonSeries": "Multiply",
    "dayTitle": "Do You Love Me",
    "reference": "John 21:9-13 ESV",
    "accent": "#C8A96E",
    "dayNum": 3,
    "publishDate": "2026-02-25"
  },
  "do-you-love-me/4": {
    "weekTitle": "Do You Love Me",
    "sermonSeries": "Multiply",
    "dayTitle": "Do You Love Me",
    "reference": "John 21:15-17 ESV",
    "accent": "#C8A96E",
    "dayNum": 4,
    "publishDate": "2026-02-26"
  },
  "do-you-love-me/5": {
    "weekTitle": "Do You Love Me",
    "sermonSeries": "Multiply",
    "dayTitle": "Do You Love Me",
    "reference": "John 21:17-19 ESV",
    "accent": "#C8A96E",
    "dayNum": 5,
    "publishDate": "2026-02-27"
  },
  "the-ephesus-effect/1": {
    "weekTitle": "The Ephesus Effect",
    "sermonSeries": "Multiply",
    "dayTitle": "The Ephesus Effect",
    "reference": "Acts 19:8-10 ESV",
    "accent": "#C8A96E",
    "dayNum": 1,
    "publishDate": "2026-02-16"
  },
  "the-ephesus-effect/2": {
    "weekTitle": "The Ephesus Effect",
    "sermonSeries": "Multiply",
    "dayTitle": "The Ephesus Effect",
    "reference": "Matthew 28:18-20 ESV",
    "accent": "#C8A96E",
    "dayNum": 2,
    "publishDate": "2026-02-17"
  },
  "the-ephesus-effect/3": {
    "weekTitle": "The Ephesus Effect",
    "sermonSeries": "Multiply",
    "dayTitle": "The Ephesus Effect",
    "reference": "Acts 19:18-19 ESV",
    "accent": "#C8A96E",
    "dayNum": 3,
    "publishDate": "2026-02-18"
  },
  "the-ephesus-effect/4": {
    "weekTitle": "The Ephesus Effect",
    "sermonSeries": "Multiply",
    "dayTitle": "The Ephesus Effect",
    "reference": "Colossians 1:3-7 ESV",
    "accent": "#C8A96E",
    "dayNum": 4,
    "publishDate": "2026-02-19"
  },
  "the-ephesus-effect/5": {
    "weekTitle": "The Ephesus Effect",
    "sermonSeries": "Multiply",
    "dayTitle": "The Ephesus Effect",
    "reference": "Colossians 4:12-13 ESV",
    "accent": "#C8A96E",
    "dayNum": 5,
    "publishDate": "2026-02-20"
  },
  "whose-fruit-is-it/1": {
    "weekTitle": "Whose Fruit Is It",
    "sermonSeries": "Multiply",
    "dayTitle": "Whose Fruit Is It",
    "reference": "Matthew 21:33 ESV ESV",
    "accent": "#C8A96E",
    "dayNum": 1,
    "publishDate": "2026-02-09"
  },
  "whose-fruit-is-it/2": {
    "weekTitle": "Whose Fruit Is It",
    "sermonSeries": "Multiply",
    "dayTitle": "Whose Fruit Is It",
    "reference": "Matthew 21:34 ESV ESV",
    "accent": "#C8A96E",
    "dayNum": 2,
    "publishDate": "2026-02-10"
  },
  "whose-fruit-is-it/3": {
    "weekTitle": "Whose Fruit Is It",
    "sermonSeries": "Multiply",
    "dayTitle": "Whose Fruit Is It",
    "reference": "Matthew 21:35-39 ESV ESV",
    "accent": "#C8A96E",
    "dayNum": 3,
    "publishDate": "2026-02-11"
  },
  "whose-fruit-is-it/4": {
    "weekTitle": "Whose Fruit Is It",
    "sermonSeries": "Multiply",
    "dayTitle": "Whose Fruit Is It",
    "reference": "Matthew 21:43 ESV ESV",
    "accent": "#C8A96E",
    "dayNum": 4,
    "publishDate": "2026-02-12"
  },
  "whose-fruit-is-it/5": {
    "weekTitle": "Whose Fruit Is It",
    "sermonSeries": "Multiply",
    "dayTitle": "Whose Fruit Is It",
    "reference": "Luke 12:48 ESV ESV",
    "accent": "#C8A96E",
    "dayNum": 5,
    "publishDate": "2026-02-13"
  },
  "the-first-command/1": {
    "weekTitle": "The First Command",
    "sermonSeries": "Multiply",
    "dayTitle": "The First Command",
    "reference": "Genesis 1:28 ESV",
    "accent": "#C8A96E",
    "dayNum": 1,
    "publishDate": "2026-02-01"
  },
  "the-first-command/2": {
    "weekTitle": "The First Command",
    "sermonSeries": "Multiply",
    "dayTitle": "The First Command",
    "reference": "Ephesians 2:10 ESV",
    "accent": "#C8A96E",
    "dayNum": 2,
    "publishDate": "2026-02-02"
  },
  "the-first-command/3": {
    "weekTitle": "The First Command",
    "sermonSeries": "Multiply",
    "dayTitle": "The First Command",
    "reference": "Genesis 9:1 ESV",
    "accent": "#C8A96E",
    "dayNum": 3,
    "publishDate": "2026-02-04"
  },
  "the-first-command/4": {
    "weekTitle": "The First Command",
    "sermonSeries": "Multiply",
    "dayTitle": "The First Command",
    "reference": "Matthew 28:18-20 ESV",
    "accent": "#C8A96E",
    "dayNum": 4,
    "publishDate": "2026-02-05"
  },
  "the-first-command/5": {
    "weekTitle": "The First Command",
    "sermonSeries": "Multiply",
    "dayTitle": "The First Command",
    "reference": "Mark 4:30-32 ESV",
    "accent": "#C8A96E",
    "dayNum": 5,
    "publishDate": "2026-02-06"
  },
  "not-a-pause-a-pursuit/1": {
    "weekTitle": "Not a Pause, a Pursuit",
    "sermonSeries": "Seek First",
    "dayTitle": "Not a Pause, a Pursuit",
    "reference": "1 Samuel 7:11 ESV",
    "accent": "#181818",
    "dayNum": 1,
    "publishDate": "2026-01-26"
  },
  "not-a-pause-a-pursuit/2": {
    "weekTitle": "Not a Pause, a Pursuit",
    "sermonSeries": "Seek First",
    "dayTitle": "Not a Pause, a Pursuit",
    "reference": "Philippians 3:7-8 ESV",
    "accent": "#181818",
    "dayNum": 2,
    "publishDate": "2026-01-26"
  },
  "not-a-pause-a-pursuit/3": {
    "weekTitle": "Not a Pause, a Pursuit",
    "sermonSeries": "Seek First",
    "dayTitle": "Not a Pause, a Pursuit",
    "reference": "Philippians 3:12 CSB",
    "accent": "#181818",
    "dayNum": 3,
    "publishDate": "2026-01-27"
  },
  "not-a-pause-a-pursuit/4": {
    "weekTitle": "Not a Pause, a Pursuit",
    "sermonSeries": "Seek First",
    "dayTitle": "Not a Pause, a Pursuit",
    "reference": "Philippians 3:13-14 CSB",
    "accent": "#181818",
    "dayNum": 4,
    "publishDate": "2026-01-28"
  },
  "not-a-pause-a-pursuit/5": {
    "weekTitle": "Not a Pause, a Pursuit",
    "sermonSeries": "Seek First",
    "dayTitle": "Not a Pause, a Pursuit",
    "reference": "Philippians 3:18-19 ESV",
    "accent": "#181818",
    "dayNum": 5,
    "publishDate": "2026-01-29"
  },
  "the-fast-that/1": {
    "weekTitle": "The Fast That",
    "sermonSeries": "Seek First",
    "dayTitle": "The Fast That",
    "reference": "Isaiah 58:2 ESV",
    "accent": "#181818",
    "dayNum": 1,
    "publishDate": "2026-01-18"
  },
  "the-fast-that/2": {
    "weekTitle": "The Fast That",
    "sermonSeries": "Seek First",
    "dayTitle": "The Fast That",
    "reference": "Isaiah 58:3 ESV",
    "accent": "#181818",
    "dayNum": 2,
    "publishDate": "2026-01-19"
  },
  "the-fast-that/3": {
    "weekTitle": "The Fast That",
    "sermonSeries": "Seek First",
    "dayTitle": "The Fast That",
    "reference": "Isaiah 58:6-7 ESV",
    "accent": "#181818",
    "dayNum": 3,
    "publishDate": "2026-01-20"
  },
  "the-fast-that/4": {
    "weekTitle": "The Fast That",
    "sermonSeries": "Seek First",
    "dayTitle": "The Fast That",
    "reference": "Philippians 2:6-7 ESV",
    "accent": "#181818",
    "dayNum": 4,
    "publishDate": "2026-01-22"
  },
  "the-fast-that/5": {
    "weekTitle": "The Fast That",
    "sermonSeries": "Seek First",
    "dayTitle": "The Fast That",
    "reference": "Isaiah 58:12 ESV",
    "accent": "#181818",
    "dayNum": 5,
    "publishDate": "2026-01-24"
  },
  "before-you-seek-return/1": {
    "weekTitle": "Before You Seek, Return",
    "sermonSeries": "Seek First",
    "dayTitle": "Before You Seek, Return",
    "reference": "1 Samuel 7:3 ESV",
    "accent": "#181818",
    "dayNum": 1,
    "publishDate": "2026-01-04"
  },
  "before-you-seek-return/2": {
    "weekTitle": "Before You Seek, Return",
    "sermonSeries": "Seek First",
    "dayTitle": "Before You Seek, Return",
    "reference": "Proverbs 4:23 ESV",
    "accent": "#181818",
    "dayNum": 2,
    "publishDate": "2026-01-05"
  },
  "before-you-seek-return/3": {
    "weekTitle": "Before You Seek, Return",
    "sermonSeries": "Seek First",
    "dayTitle": "Before You Seek, Return",
    "reference": "Romans 7:19 ESV",
    "accent": "#181818",
    "dayNum": 3,
    "publishDate": "2026-01-06"
  },
  "before-you-seek-return/4": {
    "weekTitle": "Before You Seek, Return",
    "sermonSeries": "Seek First",
    "dayTitle": "Before You Seek, Return",
    "reference": "1 Corinthians 10:6 ESV",
    "accent": "#181818",
    "dayNum": 4,
    "publishDate": "2026-01-07"
  },
  "before-you-seek-return/5": {
    "weekTitle": "Before You Seek, Return",
    "sermonSeries": "Seek First",
    "dayTitle": "Before You Seek, Return",
    "reference": "Isaiah 43:10-11 ESV",
    "accent": "#181818",
    "dayNum": 5,
    "publishDate": "2026-01-08"
  },
  "foundations-of-true-discipleship/1": {
    "weekTitle": "Foundations of True Discipleship",
    "sermonSeries": "Foundations",
    "dayTitle": "The Gate That Demands Everything",
    "reference": "Matthew 7:13-14 ESV",
    "accent": "#998178",
    "dayNum": 1,
    "publishDate": "2025-11-23"
  },
  "foundations-of-true-discipleship/2": {
    "weekTitle": "Foundations of True Discipleship",
    "sermonSeries": "Foundations",
    "dayTitle": "The Fruit That Reveals Everything",
    "reference": "Matthew 7:16-20 ESV",
    "accent": "#998178",
    "dayNum": 2,
    "publishDate": "2025-11-24"
  },
  "foundations-of-true-discipleship/3": {
    "weekTitle": "Foundations of True Discipleship",
    "sermonSeries": "Foundations",
    "dayTitle": "The Lord Who Knows Everything",
    "reference": "Matthew 7:21-23 ESV",
    "accent": "#998178",
    "dayNum": 3,
    "publishDate": "2025-11-25"
  },
  "foundations-of-true-discipleship/4": {
    "weekTitle": "Foundations of True Discipleship",
    "sermonSeries": "Foundations",
    "dayTitle": "The Foundation That Holds Everything",
    "reference": "Matthew 7:24-27 ESV",
    "accent": "#998178",
    "dayNum": 4,
    "publishDate": "2025-11-26"
  },
  "foundations-of-true-discipleship/5": {
    "weekTitle": "Foundations of True Discipleship",
    "sermonSeries": "Foundations",
    "dayTitle": "The Storm That Tests Everything",
    "reference": "Matthew 7:28-29 ESV",
    "accent": "#998178",
    "dayNum": 5,
    "publishDate": "2025-11-27"
  },
  "father-knows-best/1": {
    "weekTitle": "Father Knows Best",
    "sermonSeries": "Foundations",
    "dayTitle": "When Prayer Feels Pointless",
    "reference": "Matthew 7:7–8 ESV",
    "accent": "#998178",
    "dayNum": 1,
    "publishDate": "2025-11-16"
  },
  "father-knows-best/2": {
    "weekTitle": "Father Knows Best",
    "sermonSeries": "Foundations",
    "dayTitle": "The Command to Keep Asking",
    "reference": "Matthew 7:7–8 ESV",
    "accent": "#998178",
    "dayNum": 2,
    "publishDate": "2025-11-17"
  },
  "father-knows-best/3": {
    "weekTitle": "Father Knows Best",
    "sermonSeries": "Foundations",
    "dayTitle": "Bread, Stones, and What We're Really Asking For",
    "reference": "Matthew 7:9-10 ESV",
    "accent": "#998178",
    "dayNum": 3,
    "publishDate": "2025-11-18"
  },
  "father-knows-best/4": {
    "weekTitle": "Father Knows Best",
    "sermonSeries": "Foundations",
    "dayTitle": "How Much More",
    "reference": "Matthew 7:11 ESV",
    "accent": "#998178",
    "dayNum": 4,
    "publishDate": "2025-11-20"
  },
  "father-knows-best/5": {
    "weekTitle": "Father Knows Best",
    "sermonSeries": "Foundations",
    "dayTitle": "Resume Asking",
    "reference": "Philippians 3:8–10 ESV",
    "accent": "#998178",
    "dayNum": 5,
    "publishDate": "2025-11-21"
  },
  "the-way-of-discernment/1": {
    "weekTitle": "The Way of Discernment",
    "sermonSeries": "Foundations",
    "dayTitle": "Called to Discern",
    "reference": "Matthew 7:1-2 ESV",
    "accent": "#998178",
    "dayNum": 1,
    "publishDate": "2025-11-09"
  },
  "the-way-of-discernment/2": {
    "weekTitle": "The Way of Discernment",
    "sermonSeries": "Foundations",
    "dayTitle": "Clearing Your Vision",
    "reference": "Matthew 7:3-5 ESV",
    "accent": "#998178",
    "dayNum": 2,
    "publishDate": "2025-11-10"
  },
  "the-way-of-discernment/3": {
    "weekTitle": "The Way of Discernment",
    "sermonSeries": "Foundations",
    "dayTitle": "When Ignorance Blinds",
    "reference": "1 Corinthians 4:3-5 ESV",
    "accent": "#998178",
    "dayNum": 3,
    "publishDate": "2025-11-11"
  },
  "the-way-of-discernment/4": {
    "weekTitle": "The Way of Discernment",
    "sermonSeries": "Foundations",
    "dayTitle": "The Power of Compassion",
    "reference": "James 2:12-13 ESV",
    "accent": "#998178",
    "dayNum": 4,
    "publishDate": "2025-11-12"
  },
  "the-way-of-discernment/5": {
    "weekTitle": "The Way of Discernment",
    "sermonSeries": "Foundations",
    "dayTitle": "Wisdom in Discernment",
    "reference": "Matthew 7:6 ESV",
    "accent": "#998178",
    "dayNum": 5,
    "publishDate": "2025-11-13"
  },
  "the-lies-anxiety-tells/1": {
    "weekTitle": "The Lies Anxiety Tells",
    "sermonSeries": "Foundations",
    "dayTitle": "What Is Anxiety Really Telling You?",
    "reference": "Matthew 6:25 ESV",
    "accent": "#998178",
    "dayNum": 1,
    "publishDate": "2025-11-02"
  },
  "the-lies-anxiety-tells/2": {
    "weekTitle": "The Lies Anxiety Tells",
    "sermonSeries": "Foundations",
    "dayTitle": "More Blessed Than Birds",
    "reference": "Matthew 6:27-28 ESV",
    "accent": "#998178",
    "dayNum": 2,
    "publishDate": "2025-11-03"
  },
  "the-lies-anxiety-tells/3": {
    "weekTitle": "The Lies Anxiety Tells",
    "sermonSeries": "Foundations",
    "dayTitle": "More Loved Than Lilies",
    "reference": "Matthew 6:28-30 ESV",
    "accent": "#998178",
    "dayNum": 3,
    "publishDate": "2025-11-04"
  },
  "the-lies-anxiety-tells/4": {
    "weekTitle": "The Lies Anxiety Tells",
    "sermonSeries": "Foundations",
    "dayTitle": "Seeking What Actually Matters",
    "reference": "Matthew 6:33 ESV",
    "accent": "#998178",
    "dayNum": 4,
    "publishDate": "2025-11-05"
  },
  "the-lies-anxiety-tells/5": {
    "weekTitle": "The Lies Anxiety Tells",
    "sermonSeries": "Foundations",
    "dayTitle": "When Thanksgiving Changes Everything",
    "reference": "Philippians 4:6 ESV",
    "accent": "#998178",
    "dayNum": 5,
    "publishDate": "2025-11-06"
  },
  "the-treasures-that-betray-us/1": {
    "weekTitle": "The Treasures That Betray Us",
    "sermonSeries": "Foundations",
    "dayTitle": "Where Your Treasure Hides",
    "reference": "Matthew 6:19-21 ESV",
    "accent": "#998178",
    "dayNum": 1,
    "publishDate": "2025-10-26"
  },
  "the-treasures-that-betray-us/2": {
    "weekTitle": "The Treasures That Betray Us",
    "sermonSeries": "Foundations",
    "dayTitle": "The Vision That Blinds You",
    "reference": "Matthew 6:22-23 ESV",
    "accent": "#998178",
    "dayNum": 2,
    "publishDate": "2025-10-27"
  },
  "the-treasures-that-betray-us/3": {
    "weekTitle": "The Treasures That Betray Us",
    "sermonSeries": "Foundations",
    "dayTitle": "The Grace You Profess, The Works You Practice",
    "reference": "Matthew 20:15 ESV",
    "accent": "#998178",
    "dayNum": 3,
    "publishDate": "2025-10-28"
  },
  "the-treasures-that-betray-us/4": {
    "weekTitle": "The Treasures That Betray Us",
    "sermonSeries": "Foundations",
    "dayTitle": "The Comparison That Corrupts You",
    "reference": "Galatians 6:4-5 ESV",
    "accent": "#998178",
    "dayNum": 4,
    "publishDate": "2025-10-29"
  },
  "the-treasures-that-betray-us/5": {
    "weekTitle": "The Treasures That Betray Us",
    "sermonSeries": "Foundations",
    "dayTitle": "The Surrender That Sets You Free",
    "reference": "Matthew 6:33 ESV",
    "accent": "#998178",
    "dayNum": 5,
    "publishDate": "2025-10-30"
  },
  "approval-or-acceptance/1": {
    "weekTitle": "Approval or Acceptance",
    "sermonSeries": "Foundations",
    "dayTitle": "The Foundation Question: Approval or Acceptance?",
    "reference": "Romans 8:14-16 ESV",
    "accent": "#998178",
    "dayNum": 1,
    "publishDate": "2025-10-20"
  },
  "approval-or-acceptance/2": {
    "weekTitle": "Approval or Acceptance",
    "sermonSeries": "Foundations",
    "dayTitle": "Giving from Gratitude, Not for Glory",
    "reference": "Matthew 6:1-4 ESV",
    "accent": "#998178",
    "dayNum": 2,
    "publishDate": "2025-10-20"
  },
  "approval-or-acceptance/3": {
    "weekTitle": "Approval or Acceptance",
    "sermonSeries": "Foundations",
    "dayTitle": "Seeking Audience or Knowing You're Heard?",
    "reference": "Matthew 6:5-8 ESV",
    "accent": "#998178",
    "dayNum": 3,
    "publishDate": "2025-10-21"
  },
  "approval-or-acceptance/4": {
    "weekTitle": "Approval or Acceptance",
    "sermonSeries": "Foundations",
    "dayTitle": "Fasting for Intimacy, Not Image",
    "reference": "Matthew 6:16-18 ESV",
    "accent": "#998178",
    "dayNum": 4,
    "publishDate": "2025-10-22"
  },
  "approval-or-acceptance/5": {
    "weekTitle": "Approval or Acceptance",
    "sermonSeries": "Foundations",
    "dayTitle": "Building Your House on the Rock",
    "reference": "Matthew 7:24-27 ESV",
    "accent": "#998178",
    "dayNum": 5,
    "publishDate": "2025-10-23"
  },
  "oaths/1": {
    "weekTitle": "Oaths",
    "sermonSeries": "The Way of Perfection",
    "dayTitle": "The Call To Integrity",
    "reference": "Matthew 5:33-37 CSB",
    "accent": "#FB8C0C",
    "dayNum": 1,
    "publishDate": "2025-10-05"
  },
  "oaths/2": {
    "weekTitle": "Oaths",
    "sermonSeries": "The Way of Perfection",
    "dayTitle": "The God Card",
    "reference": "Mark 7:11-15 ESV",
    "accent": "#FB8C0C",
    "dayNum": 2,
    "publishDate": "2025-10-06"
  },
  "oaths/3": {
    "weekTitle": "Oaths",
    "sermonSeries": "The Way of Perfection",
    "dayTitle": "The Bypass Card",
    "reference": "Matthew 23:16-22 ESV",
    "accent": "#FB8C0C",
    "dayNum": 3,
    "publishDate": "2025-10-07"
  },
  "oaths/4": {
    "weekTitle": "Oaths",
    "sermonSeries": "The Way of Perfection",
    "dayTitle": "Empty Promises & Escape Hatches",
    "reference": "Numbers 30:2; Deuteronomy 23:21 ESV",
    "accent": "#FB8C0C",
    "dayNum": 4,
    "publishDate": "2025-10-08"
  },
  "oaths/5": {
    "weekTitle": "Oaths",
    "sermonSeries": "The Way of Perfection",
    "dayTitle": "Your Walk Reveals Your Worship",
    "reference": "Isaiah 48:1-2 GNT",
    "accent": "#FB8C0C",
    "dayNum": 5,
    "publishDate": "2025-10-09"
  },
  "oaths/6": {
    "weekTitle": "Oaths",
    "sermonSeries": "The Way of Perfection",
    "dayTitle": "There's Only One Way To Freedom",
    "reference": "Isaiah 50:10-11 NLT",
    "accent": "#FB8C0C",
    "dayNum": 6,
    "publishDate": "2025-10-10"
  },
  "oaths/7": {
    "weekTitle": "Oaths",
    "sermonSeries": "The Way of Perfection",
    "dayTitle": "Called To Be Free",
    "reference": "Isaiah 48:20 NLT",
    "accent": "#FB8C0C",
    "dayNum": 7,
    "publishDate": "2025-10-10"
  },
  "permission-vs-perfection/1": {
    "weekTitle": "Permission vs Perfection",
    "sermonSeries": "The Way of Perfection",
    "dayTitle": "Looking for Loopholes",
    "reference": "Matthew 5:31-32 ESV",
    "accent": "#FB8C0C",
    "dayNum": 1,
    "publishDate": "2025-09-28"
  },
  "permission-vs-perfection/2": {
    "weekTitle": "Permission vs Perfection",
    "sermonSeries": "The Way of Perfection",
    "dayTitle": "When Hearts Go Hard",
    "reference": "Matthew 19:8 ESV",
    "accent": "#FB8C0C",
    "dayNum": 2,
    "publishDate": "2025-09-29"
  },
  "permission-vs-perfection/3": {
    "weekTitle": "Permission vs Perfection",
    "sermonSeries": "The Way of Perfection",
    "dayTitle": "Contract or Covenant?",
    "reference": "Galatians 5:13 ESV",
    "accent": "#FB8C0C",
    "dayNum": 3,
    "publishDate": "2025-09-30"
  },
  "permission-vs-perfection/4": {
    "weekTitle": "Permission vs Perfection",
    "sermonSeries": "The Way of Perfection",
    "dayTitle": "Minimum or Maximum?",
    "reference": "Malachi 2:15 ESV",
    "accent": "#FB8C0C",
    "dayNum": 4,
    "publishDate": "2025-10-01"
  },
  "permission-vs-perfection/5": {
    "weekTitle": "Permission vs Perfection",
    "sermonSeries": "The Way of Perfection",
    "dayTitle": "Permission to Perfection",
    "reference": "Titus 2:11-12 ESV",
    "accent": "#FB8C0C",
    "dayNum": 5,
    "publishDate": "2025-10-02"
  },
  "righteousness-of-the-heart/1": {
    "weekTitle": "Righteousness of the Heart",
    "sermonSeries": "The Way of Perfection",
    "dayTitle": "Clean Cups and Pure Hearts",
    "reference": "Matthew 5:27-28 ESV",
    "accent": "#FB8C0C",
    "dayNum": 1,
    "publishDate": "2025-09-14"
  },
  "righteousness-of-the-heart/2": {
    "weekTitle": "Righteousness of the Heart",
    "sermonSeries": "The Way of Perfection",
    "dayTitle": "The Anatomy of Temptation",
    "reference": "James 1:14-15 ESV",
    "accent": "#FB8C0C",
    "dayNum": 2,
    "publishDate": "2025-09-15"
  },
  "righteousness-of-the-heart/3": {
    "weekTitle": "Righteousness of the Heart",
    "sermonSeries": "The Way of Perfection",
    "dayTitle": "Radical Surgery for the Soul",
    "reference": "Matthew 5:29-30 ESV",
    "accent": "#FB8C0C",
    "dayNum": 3,
    "publishDate": "2025-09-16"
  },
  "righteousness-of-the-heart/4": {
    "weekTitle": "Righteousness of the Heart",
    "sermonSeries": "The Way of Perfection",
    "dayTitle": "Building Fences, Guarding Hearts",
    "reference": "1 Corinthians 6:18 ESV",
    "accent": "#FB8C0C",
    "dayNum": 4,
    "publishDate": "2025-09-18"
  },
  "righteousness-of-the-heart/5": {
    "weekTitle": "Righteousness of the Heart",
    "sermonSeries": "The Way of Perfection",
    "dayTitle": "Grace for the Guilty",
    "reference": "Romans 3:23-24 ESV",
    "accent": "#FB8C0C",
    "dayNum": 5,
    "publishDate": "2025-09-18"
  },
  "murder-in-the-making/1": {
    "weekTitle": "Murder in the Making",
    "sermonSeries": "The Way of Perfection",
    "dayTitle": "Murder Starts in the Heart",
    "reference": "Matthew 5:21-22 ESV",
    "accent": "#FB8C0C",
    "dayNum": 1,
    "publishDate": "2025-09-07"
  },
  "murder-in-the-making/2": {
    "weekTitle": "Murder in the Making",
    "sermonSeries": "The Way of Perfection",
    "dayTitle": "The First Step",
    "reference": "Ephesians 4:31 ESV",
    "accent": "#FB8C0C",
    "dayNum": 2,
    "publishDate": "2025-09-08"
  },
  "murder-in-the-making/3": {
    "weekTitle": "Murder in the Making",
    "sermonSeries": "The Way of Perfection",
    "dayTitle": "The Slow Burn",
    "reference": "Romans 1:18 ESV",
    "accent": "#FB8C0C",
    "dayNum": 3,
    "publishDate": "2025-09-10"
  },
  "murder-in-the-making/4": {
    "weekTitle": "Murder in the Making",
    "sermonSeries": "The Way of Perfection",
    "dayTitle": "When Anger Explodes",
    "reference": "Matthew 5:22 ESV",
    "accent": "#FB8C0C",
    "dayNum": 4,
    "publishDate": "2025-09-10"
  },
  "murder-in-the-making/5": {
    "weekTitle": "Murder in the Making",
    "sermonSeries": "The Way of Perfection",
    "dayTitle": "When We Raise Our Voice",
    "reference": "Ephesians 4:26-27, 31 ESV",
    "accent": "#FB8C0C",
    "dayNum": 5,
    "publishDate": "2025-09-11"
  },
  "murder-in-the-making/6": {
    "weekTitle": "Murder in the Making",
    "sermonSeries": "The Way of Perfection",
    "dayTitle": "Tearing Others Down",
    "reference": "John 8:48; Matthew 12:24 ESV",
    "accent": "#FB8C0C",
    "dayNum": 6,
    "publishDate": "2025-09-12"
  },
  "murder-in-the-making/7": {
    "weekTitle": "Murder in the Making",
    "sermonSeries": "The Way of Perfection",
    "dayTitle": "Making Things Right",
    "reference": "Matthew 5:23-24 ESV",
    "accent": "#FB8C0C",
    "dayNum": 7,
    "publishDate": "2025-09-13"
  },
  "recognizing-true-righteousness/1": {
    "weekTitle": "Recognizing True Righteousness",
    "sermonSeries": "Influence",
    "dayTitle": "Recognizing True Righteousness",
    "reference": "Matthew 5:17-20 ESV",
    "accent": "#302752",
    "dayNum": 1,
    "publishDate": "2025-08-31"
  },
  "recognizing-true-righteousness/2": {
    "weekTitle": "Recognizing True Righteousness",
    "sermonSeries": "Influence",
    "dayTitle": "Recognizing True Righteousness",
    "reference": "Romans 3:23-26 ESV",
    "accent": "#302752",
    "dayNum": 2,
    "publishDate": "2025-09-01"
  },
  "recognizing-true-righteousness/3": {
    "weekTitle": "Recognizing True Righteousness",
    "sermonSeries": "Influence",
    "dayTitle": "Recognizing True Righteousness",
    "reference": "Philippians 2:8 ESV",
    "accent": "#302752",
    "dayNum": 3,
    "publishDate": "2025-09-02"
  },
  "recognizing-true-righteousness/4": {
    "weekTitle": "Recognizing True Righteousness",
    "sermonSeries": "Influence",
    "dayTitle": "Recognizing True Righteousness",
    "reference": "Romans 8:3-4 ESV",
    "accent": "#302752",
    "dayNum": 4,
    "publishDate": "2025-09-03"
  },
  "recognizing-true-righteousness/5": {
    "weekTitle": "Recognizing True Righteousness",
    "sermonSeries": "Influence",
    "dayTitle": "Recognizing True Righteousness",
    "reference": "Matthew 5:19 ESV",
    "accent": "#302752",
    "dayNum": 5,
    "publishDate": "2025-09-04"
  },
  "recognizing-true-righteousness/6": {
    "weekTitle": "Recognizing True Righteousness",
    "sermonSeries": "Influence",
    "dayTitle": "Recognizing True Righteousness",
    "reference": "Matthew 5:20 ESV",
    "accent": "#302752",
    "dayNum": 6,
    "publishDate": "2025-09-05"
  },
  "you-are-the-light/1": {
    "weekTitle": "You Are the Light of the World",
    "sermonSeries": "Influence",
    "dayTitle": "You Are the Light of the World",
    "reference": "Matthew 5:14 ESV",
    "accent": "#302752",
    "dayNum": 1,
    "publishDate": "2025-08-18"
  },
  "you-are-the-light/2": {
    "weekTitle": "You Are the Light of the World",
    "sermonSeries": "Influence",
    "dayTitle": "You Are the Light of the World",
    "reference": "John 1:5 ESV",
    "accent": "#302752",
    "dayNum": 2,
    "publishDate": "2025-08-19"
  },
  "you-are-the-light/3": {
    "weekTitle": "You Are the Light of the World",
    "sermonSeries": "Influence",
    "dayTitle": "You Are the Light of the World",
    "reference": "Matthew 5:14 ESV",
    "accent": "#302752",
    "dayNum": 3,
    "publishDate": "2025-08-20"
  },
  "you-are-the-light/4": {
    "weekTitle": "You Are the Light of the World",
    "sermonSeries": "Influence",
    "dayTitle": "You Are the Light of the World",
    "reference": "Matthew 5:15 ESV",
    "accent": "#302752",
    "dayNum": 4,
    "publishDate": "2025-08-20"
  },
  "you-are-the-light/5": {
    "weekTitle": "You Are the Light of the World",
    "sermonSeries": "Influence",
    "dayTitle": "You Are the Light of the World",
    "reference": "Matthew 5:14-16 ESV",
    "accent": "#302752",
    "dayNum": 5,
    "publishDate": "2025-08-22"
  },
  "still-salty/1": {
    "weekTitle": "Still Salty",
    "sermonSeries": "Influence",
    "dayTitle": "Still Salty",
    "reference": "Matthew 5:13 ESV",
    "accent": "#302752",
    "dayNum": 1,
    "publishDate": "2025-08-10"
  },
  "still-salty/2": {
    "weekTitle": "Still Salty",
    "sermonSeries": "Influence",
    "dayTitle": "Still Salty",
    "reference": "Matthew 5:13 ESV",
    "accent": "#302752",
    "dayNum": 2,
    "publishDate": "2025-08-11"
  },
  "still-salty/3": {
    "weekTitle": "Still Salty",
    "sermonSeries": "Influence",
    "dayTitle": "Still Salty",
    "reference": "Numbers 18:19 ESV",
    "accent": "#302752",
    "dayNum": 3,
    "publishDate": "2025-08-12"
  },
  "still-salty/4": {
    "weekTitle": "Still Salty",
    "sermonSeries": "Influence",
    "dayTitle": "Still Salty",
    "reference": "Matthew 5:13 ESV",
    "accent": "#302752",
    "dayNum": 4,
    "publishDate": "2025-08-13"
  },
  "still-salty/5": {
    "weekTitle": "Still Salty",
    "sermonSeries": "Influence",
    "dayTitle": "Still Salty",
    "reference": "Colossians 4:5–6 ESV",
    "accent": "#302752",
    "dayNum": 5,
    "publishDate": "2025-08-14"
  },
  "stay-salty/1": {
    "weekTitle": "Stay Salty",
    "sermonSeries": "Influence",
    "dayTitle": "Stay Salty",
    "reference": "Matthew 5:13a ESV",
    "accent": "#302752",
    "dayNum": 1,
    "publishDate": "2025-08-03"
  },
  "stay-salty/2": {
    "weekTitle": "Stay Salty",
    "sermonSeries": "Influence",
    "dayTitle": "Stay Salty",
    "reference": "ESV",
    "accent": "#302752",
    "dayNum": 2,
    "publishDate": "2025-08-05"
  },
  "stay-salty/3": {
    "weekTitle": "Stay Salty",
    "sermonSeries": "Influence",
    "dayTitle": "Stay Salty",
    "reference": "Mark 9:50 ESV",
    "accent": "#302752",
    "dayNum": 3,
    "publishDate": "2025-08-05"
  },
  "stay-salty/4": {
    "weekTitle": "Stay Salty",
    "sermonSeries": "Influence",
    "dayTitle": "Stay Salty",
    "reference": "John 7:37–38 ESV",
    "accent": "#302752",
    "dayNum": 4,
    "publishDate": "2025-08-06"
  },
  "stay-salty/5": {
    "weekTitle": "Stay Salty",
    "sermonSeries": "Influence",
    "dayTitle": "Stay Salty",
    "reference": "Matthew 5:13 ESV",
    "accent": "#302752",
    "dayNum": 5,
    "publishDate": "2025-08-07"
  },
  "blessed-are-the-persecuted/1": {
    "weekTitle": "Blessed are the Persecuted",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "Blessed are the Persecuted",
    "reference": "Matthew 5:10 ESV",
    "accent": "#D28D52",
    "dayNum": 1,
    "publishDate": "2025-07-27"
  },
  "blessed-are-the-persecuted/2": {
    "weekTitle": "Blessed are the Persecuted",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "Blessed are the Persecuted",
    "reference": "John 15:19–20 ESV",
    "accent": "#D28D52",
    "dayNum": 2,
    "publishDate": "2025-07-28"
  },
  "blessed-are-the-persecuted/3": {
    "weekTitle": "Blessed are the Persecuted",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "Blessed are the Persecuted",
    "reference": "Matthew 5:11 ESV",
    "accent": "#D28D52",
    "dayNum": 3,
    "publishDate": "2025-07-29"
  },
  "blessed-are-the-persecuted/4": {
    "weekTitle": "Blessed are the Persecuted",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "Blessed are the Persecuted",
    "reference": "Daniel 3:17–18 ESV",
    "accent": "#D28D52",
    "dayNum": 4,
    "publishDate": "2025-07-31"
  },
  "blessed-are-the-persecuted/5": {
    "weekTitle": "Blessed are the Persecuted",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "Blessed are the Persecuted",
    "reference": "Matthew 5:12 ESV",
    "accent": "#D28D52",
    "dayNum": 5,
    "publishDate": "2025-08-01"
  },
  "the-pattern-of-peacemaking/1": {
    "weekTitle": "The Pattern of Peacemaking",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "The Pattern of Peacemaking",
    "reference": "Isaiah 66:12 ESV",
    "accent": "#D28D52",
    "dayNum": 1,
    "publishDate": "2025-07-21"
  },
  "the-pattern-of-peacemaking/2": {
    "weekTitle": "The Pattern of Peacemaking",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "The Pattern of Peacemaking",
    "reference": "Luke 10:5 ESV",
    "accent": "#D28D52",
    "dayNum": 2,
    "publishDate": "2025-07-22"
  },
  "the-pattern-of-peacemaking/3": {
    "weekTitle": "The Pattern of Peacemaking",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "The Pattern of Peacemaking",
    "reference": "ESV",
    "accent": "#D28D52",
    "dayNum": 3,
    "publishDate": "2025-07-22"
  },
  "the-pattern-of-peacemaking/4": {
    "weekTitle": "The Pattern of Peacemaking",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "The Pattern of Peacemaking",
    "reference": "Ephesians 5:25–26 ESV",
    "accent": "#D28D52",
    "dayNum": 4,
    "publishDate": "2025-07-23"
  },
  "the-pattern-of-peacemaking/5": {
    "weekTitle": "The Pattern of Peacemaking",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "The Pattern of Peacemaking",
    "reference": "Ephesians 6:1–4 ESV",
    "accent": "#D28D52",
    "dayNum": 5,
    "publishDate": "2025-07-24"
  },
  "the-peacemakers/1": {
    "weekTitle": "The Peacemakers",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "The Peacemakers",
    "reference": "Ephesians 2:14 ESV",
    "accent": "#D28D52",
    "dayNum": 1,
    "publishDate": "2025-07-13"
  },
  "the-peacemakers/2": {
    "weekTitle": "The Peacemakers",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "The Peacemakers",
    "reference": "Ezekiel 13:10 ESV",
    "accent": "#D28D52",
    "dayNum": 2,
    "publishDate": "2025-07-15"
  },
  "the-peacemakers/3": {
    "weekTitle": "The Peacemakers",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "The Peacemakers",
    "reference": "James 4:1 ESV",
    "accent": "#D28D52",
    "dayNum": 3,
    "publishDate": "2025-07-16"
  },
  "the-peacemakers/4": {
    "weekTitle": "The Peacemakers",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "The Peacemakers",
    "reference": "Isaiah 26:3 ESV",
    "accent": "#D28D52",
    "dayNum": 4,
    "publishDate": "2025-07-17"
  },
  "the-peacemakers/5": {
    "weekTitle": "The Peacemakers",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "The Peacemakers",
    "reference": "Matthew 5:9 ESV",
    "accent": "#D28D52",
    "dayNum": 5,
    "publishDate": "2025-07-18"
  },
  "the-pure-in-heart/1": {
    "weekTitle": "The Pure In Heart",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "The Pure In Heart",
    "reference": "Matthew 5:8 ESV",
    "accent": "#D28D52",
    "dayNum": 1,
    "publishDate": "2025-07-07"
  },
  "the-pure-in-heart/2": {
    "weekTitle": "The Pure In Heart",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "The Pure In Heart",
    "reference": "James 4:8 ESV",
    "accent": "#D28D52",
    "dayNum": 2,
    "publishDate": "2025-07-08"
  },
  "the-pure-in-heart/3": {
    "weekTitle": "The Pure In Heart",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "The Pure In Heart",
    "reference": "Proverbs 4:23 NLT",
    "accent": "#D28D52",
    "dayNum": 3,
    "publishDate": "2025-07-08"
  },
  "the-pure-in-heart/4": {
    "weekTitle": "The Pure In Heart",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "The Pure In Heart",
    "reference": "Job 42:5 ESV",
    "accent": "#D28D52",
    "dayNum": 4,
    "publishDate": "2025-07-10"
  },
  "the-pure-in-heart/5": {
    "weekTitle": "The Pure In Heart",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "The Pure In Heart",
    "reference": "Psalm 27:8 ESV",
    "accent": "#D28D52",
    "dayNum": 5,
    "publishDate": "2025-07-10"
  },
  "compassion-in-action/1": {
    "weekTitle": "Compassion in Action",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "Compassion in Action",
    "reference": "Matthew 5:7 ESV",
    "accent": "#D28D52",
    "dayNum": 1,
    "publishDate": "2025-06-29"
  },
  "compassion-in-action/2": {
    "weekTitle": "Compassion in Action",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "Compassion in Action",
    "reference": "Luke 10:36–37 ESV",
    "accent": "#D28D52",
    "dayNum": 2,
    "publishDate": "2025-06-29"
  },
  "compassion-in-action/3": {
    "weekTitle": "Compassion in Action",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "Compassion in Action",
    "reference": "Luke 10:34–35 ESV",
    "accent": "#D28D52",
    "dayNum": 3,
    "publishDate": "2025-07-01"
  },
  "compassion-in-action/4": {
    "weekTitle": "Compassion in Action",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "Compassion in Action",
    "reference": "Luke 10:33 ESV",
    "accent": "#D28D52",
    "dayNum": 4,
    "publishDate": "2025-07-03"
  },
  "compassion-in-action/5": {
    "weekTitle": "Compassion in Action",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "Compassion in Action",
    "reference": "Matthe 5:7 ESV",
    "accent": "#D28D52",
    "dayNum": 5,
    "publishDate": "2025-07-07"
  },
  "rediscovering-our-hunger/1": {
    "weekTitle": "Rediscovering Our Hunger",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "Rediscovering Our Hunger",
    "reference": "Matthew 5:6 ESV",
    "accent": "#D28D52",
    "dayNum": 1,
    "publishDate": "2025-06-21"
  },
  "rediscovering-our-hunger/2": {
    "weekTitle": "Rediscovering Our Hunger",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "Rediscovering Our Hunger",
    "reference": "ESV",
    "accent": "#D28D52",
    "dayNum": 2,
    "publishDate": "2025-06-25"
  },
  "rediscovering-our-hunger/3": {
    "weekTitle": "Rediscovering Our Hunger",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "Rediscovering Our Hunger",
    "reference": "ESV",
    "accent": "#D28D52",
    "dayNum": 3,
    "publishDate": "2025-06-25"
  },
  "rediscovering-our-hunger/4": {
    "weekTitle": "Rediscovering Our Hunger",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "Rediscovering Our Hunger",
    "reference": "ESV",
    "accent": "#D28D52",
    "dayNum": 4,
    "publishDate": "2025-06-25"
  },
  "rediscovering-our-hunger/5": {
    "weekTitle": "Rediscovering Our Hunger",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "Rediscovering Our Hunger",
    "reference": "ESV",
    "accent": "#D28D52",
    "dayNum": 5,
    "publishDate": "2025-06-25"
  },
  "growing-in-meekness-pt-2/1": {
    "weekTitle": "Growing in Meekness Pt 2",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "Growing in Meekness Pt 2",
    "reference": "Philippians 4:11–13 ESV",
    "accent": "#D28D52",
    "dayNum": 1,
    "publishDate": "2025-06-15"
  },
  "growing-in-meekness-pt-2/2": {
    "weekTitle": "Growing in Meekness Pt 2",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "Growing in Meekness Pt 2",
    "reference": "Ecclesiastes 4:6 ESV",
    "accent": "#D28D52",
    "dayNum": 2,
    "publishDate": "2025-06-15"
  },
  "growing-in-meekness-pt-2/3": {
    "weekTitle": "Growing in Meekness Pt 2",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "Growing in Meekness Pt 2",
    "reference": "Proverbs 16:32 ESV",
    "accent": "#D28D52",
    "dayNum": 3,
    "publishDate": "2025-06-15"
  },
  "growing-in-meekness-pt-2/4": {
    "weekTitle": "Growing in Meekness Pt 2",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "Growing in Meekness Pt 2",
    "reference": "Galatians 5:22–23 ESV",
    "accent": "#D28D52",
    "dayNum": 4,
    "publishDate": "2025-06-15"
  },
  "growing-in-meekness-pt-2/5": {
    "weekTitle": "Growing in Meekness Pt 2",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "Growing in Meekness Pt 2",
    "reference": "Matthew 5:5 ESV",
    "accent": "#D28D52",
    "dayNum": 5,
    "publishDate": "2025-06-15"
  },
  "the-poor-in-spirit/1": {
    "weekTitle": "The Poor in Spirit",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "The Poor in Spirit",
    "reference": "Matthew 5:1–3 ESV",
    "accent": "#D28D52",
    "dayNum": 1,
    "publishDate": "2025-06-07"
  },
  "the-poor-in-spirit/2": {
    "weekTitle": "The Poor in Spirit",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "The Poor in Spirit",
    "reference": "Luke 16:20–21 ESV",
    "accent": "#D28D52",
    "dayNum": 2,
    "publishDate": "2025-06-07"
  },
  "the-poor-in-spirit/3": {
    "weekTitle": "The Poor in Spirit",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "The Poor in Spirit",
    "reference": "Luke 18:9–14 ESV",
    "accent": "#D28D52",
    "dayNum": 3,
    "publishDate": "2025-06-07"
  },
  "the-poor-in-spirit/4": {
    "weekTitle": "The Poor in Spirit",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "The Poor in Spirit",
    "reference": "Isaiah 6:1–5 ESV",
    "accent": "#D28D52",
    "dayNum": 4,
    "publishDate": "2025-06-07"
  },
  "the-poor-in-spirit/5": {
    "weekTitle": "The Poor in Spirit",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "The Poor in Spirit",
    "reference": "Revelation 3:17–18 ESV",
    "accent": "#D28D52",
    "dayNum": 5,
    "publishDate": "2025-06-07"
  },
  "those-who-mourn/1": {
    "weekTitle": "Those Who Mourn",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "Those Who Mourn",
    "reference": "Matthew 5:4 ESV",
    "accent": "#D28D52",
    "dayNum": 1,
    "publishDate": "2025-06-02"
  },
  "those-who-mourn/2": {
    "weekTitle": "Those Who Mourn",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "Those Who Mourn",
    "reference": "ESV",
    "accent": "#D28D52",
    "dayNum": 2,
    "publishDate": "2025-06-02"
  },
  "those-who-mourn/3": {
    "weekTitle": "Those Who Mourn",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "Those Who Mourn",
    "reference": "Jonah 4:1–3 ESV",
    "accent": "#D28D52",
    "dayNum": 3,
    "publishDate": "2025-06-02"
  },
  "those-who-mourn/4": {
    "weekTitle": "Those Who Mourn",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "Those Who Mourn",
    "reference": "Isaiah 6:5 ESV",
    "accent": "#D28D52",
    "dayNum": 4,
    "publishDate": "2025-06-02"
  },
  "those-who-mourn/5": {
    "weekTitle": "Those Who Mourn",
    "sermonSeries": "The Way of Blessing",
    "dayTitle": "Those Who Mourn",
    "reference": "Isaiah 61:1–3 ESV",
    "accent": "#D28D52",
    "dayNum": 5,
    "publishDate": "2025-06-02"
  }
};
