import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const contentDir = path.join(__dirname, '..', 'content');
const outputFile = path.join(__dirname, '..', 'src', 'data.ts');

// ─── Parse a markdown file into a Day object ─────────────────────────────────
function parseDay(filePath) {
  const raw = fs.readFileSync(filePath, 'utf-8');
  const { data: fm, content } = matter(raw);

  // Extract sections by ## heading
  const sections = {};
  let currentSection = null;
  const lines = content.split('\n');

  for (const line of lines) {
    if (line.startsWith('## ')) {
      currentSection = line.replace('## ', '').trim().toLowerCase();
      sections[currentSection] = [];
    } else if (currentSection) {
      sections[currentSection].push(line);
    }
  }

  const getText = (key) =>
    (sections[key] || []).join('\n').trim();

  // Devotional: split into paragraphs
  const devotional = getText('devotional')
    .split(/\n\n+/)
    .map(p => p.trim())
    .filter(Boolean);

  // Application: extract numbered lines
  const questions = getText('application')
    .split('\n')
    .filter(l => /^\d+\./.test(l.trim()))
    .map(l => l.replace(/^\d+\.\s*/, '').trim());

  return {
    day: fm.day,
    title: fm.title,
    scripture: {
      reference: fm.scripture_reference,
      translation: fm.scripture_translation,
      text: fm.scripture_text,
    },
    devotional,
    questions,
    challenge: getText('challenge'),
    prayer: getText('prayer'),
    // Keep metadata for grouping
    _series: fm.series,
    _series_title: fm.series_title,
    _sermon_series: fm.sermon_series,
  };
}

// ─── Walk content directory and group into series ────────────────────────────
function buildData() {
  const sermonSeriesMap = {};

  const sermonFolders = fs.readdirSync(contentDir).filter(f =>
    fs.statSync(path.join(contentDir, f)).isDirectory()
  );

  for (const sermonFolder of sermonFolders) {
    const sermonPath = path.join(contentDir, sermonFolder);
    const weekFolders = fs.readdirSync(sermonPath).filter(f =>
      fs.statSync(path.join(sermonPath, f)).isDirectory()
    );

    for (const weekFolder of weekFolders) {
      const weekPath = path.join(sermonPath, weekFolder);
      const dayFiles = fs.readdirSync(weekPath)
        .filter(f => f.endsWith('.md'))
        .sort();

      const days = dayFiles.map(f => parseDay(path.join(weekPath, f)));
      if (!days.length) continue;

      const first = days[0];
      const sermonSeriesTitle = first._sermon_series;
      const weekSlug = weekFolder;
      const weekTitle = first._series_title;

      if (!sermonSeriesMap[sermonSeriesTitle]) {
        sermonSeriesMap[sermonSeriesTitle] = { title: sermonSeriesTitle, weeks: [] };
      }

      // Clean metadata fields off day objects
      const cleanDays = days.map(({ _series, _series_title, _sermon_series, ...rest }) => rest);

      sermonSeriesMap[sermonSeriesTitle].weeks.push({
        slug: weekSlug,
        title: weekTitle,
        sermonSeries: sermonSeriesTitle,
        days: cleanDays,
      });
    }
  }

  return Object.values(sermonSeriesMap);
}

// ─── Generate data.ts ─────────────────────────────────────────────────────────
const allSeries = buildData();

// Current series = last week of first sermon series
const currentSeriesRef = `allSeries[0].weeks[allSeries[0].weeks.length - 1]`;

const seriesColorsSource = `
export const seriesColors: Record<string, { accent: string; light: string; text: string }> = {
  "Leaving the 99": { accent: "#2D4A3E", light: "#EBF0EE", text: "#1e3329" },
  "The Shepherd's Heart": { accent: "#6B3D2E", light: "#F2EAE6", text: "#4a2a1e" },
};

export function getSeriesColor(name: string) {
  return seriesColors[name] ?? { accent: "#7a6a5a", light: "#f0ece6", text: "#4a3e34" };
}
`;

const output = `// AUTO-GENERATED by scripts/build-content.mjs — do not edit manually
// Run: node scripts/build-content.mjs

export type Day = {
  day: number;
  title: string;
  scripture: { reference: string; translation: string; text: string };
  devotional: string[];
  questions: string[];
  challenge: string;
  prayer: string;
};

export type WeeklySeries = {
  slug: string;
  title: string;
  sermonSeries: string;
  days: Day[];
};

export type SermonSeries = {
  title: string;
  weeks: WeeklySeries[];
};
${seriesColorsSource}
export const allSeries: SermonSeries[] = ${JSON.stringify(allSeries, null, 2)};

// Most recently added weekly series
export const currentSeries = ${currentSeriesRef};
`;

fs.writeFileSync(outputFile, output);
console.log(`✅ data.ts generated from ${allSeries.flatMap(s => s.weeks).length} series (${allSeries.flatMap(s => s.weeks.flatMap(w => w.days)).length} days total)`);
